### ISSUE TITLE
More Build Warning while processing  SourceKit.framework

### ISSUE THREAD

**Issue by zxl777** [huq-industries/sourcekit-ios#1]
# 

build logs

while processing /iWork/iFocus/Minecraft/PEServersApp/Pods/SourceKit/SourceKit/Frameworks/SourceKit.framework/SourceKit(HISourceKit.o):

warning: /Users/distiller/Library/Developer/Xcode/DerivedData/ModuleCache/4F6HIO926SA0/Foundation-1P52KQOIUYHCL.pcm: No such file or directory

note: Module debugging should be disabled when shipping static libraries.

while processing /iWork/iFocus/Minecraft/PEServersApp/Pods/SourceKit/SourceKit/Frameworks/SourceKit.framework/SourceKit(HISourceKit.o):

warning: /Users/distiller/Library/Developer/Xcode/DerivedData/ModuleCache/4F6HIO926SA0/CoreLocation-Y0N0XXIR98JJ.pcm: No such file or directory

while processing /iWork/iFocus/Minecraft/PEServersApp/Pods/SourceKit/SourceKit/Frameworks/SourceKit.framework/SourceKit(HISourceKit.o):

warning: /Users/distiller/Library/Developer/Xcode/DerivedData/ModuleCache/4F6HIO926SA0/SystemConfiguration-21BDC3PKOAYDE.pcm: No such file or directory

while processing /iWork/iFocus/Minecraft/PEServersApp/Pods/SourceKit/SourceKit/Frameworks/SourceKit.framework/SourceKit(HISourceKit.o):

warning: /Users/distiller/Library/Developer/Xcode/DerivedData/ModuleCache/4F6HIO926SA0/Darwin-L4YS5EU4VYTF.pcm: No such file or directory

**Comment by turbomerl** [comment]
Thanks for this. I will look at this today.

**Comment by turbomerl** [comment]
Thanks for your patience on this. I should be publishing the fix early next week. These warnings are not harmful so you can continue using the library, but I will have them removed.

**Comment by turbomerl** [comment]
I have pushed a new version of the library which should have fixed these warnings.

**Comment by zxl777** [comment]
Well Done!
Thank you
