### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jruston** [huq-industries/sourcekit-ios#5]
Hi,

I am seeing a bunch of crashes coming from this SDK, from SourceKitAds (1.1.2).

```
Exception name: EXC_SOFTWARE / UNCAUGHT_NS_EXCEPTION
__exceptionPreprocess + 1232856
objc_exception_throw + 34100
-[__NSDictionaryM setObject:forKey:] + 66836
__27-[HISourceKit submitResult]_block_invoke268 (HISourceKit.m:770)
_dispatch_call_block_and_release + 6620
_dispatch_client_callout + 6556
_dispatch_queue_override_invoke + 65744
_dispatch_root_queue_drain + 72268
_dispatch_worker_thread3 + 71628
_pthread_wqthread + 4556
start_wqthread + 3448
```

Somebody else has seen a similar crash but on a different line in your SDK:

```
__exceptionPreprocess + 1022235
objc_exception_throw + 28181
-[__NSDictionaryM setObject:forKey:] + 67801
__27-[HISourceKit submitResult]_block_invoke268 (HISourceKit.m:758)
_dispatch_call_block_and_release + 10273
_dispatch_root_queue_drain + 71143
_dispatch_worker_thread3 + 69579
_pthread_wqthread + 6951
start_wqthread + 5910
```

Would be great if you could fix it :)

Thanks!

**Comment by jruston** [comment]
As a follow up to this, it appears that it occurs in both the ads and non-ads version of the SDK and affects a reasonable number of users. Around 20% of my users could not open the app after I upgraded to 1.1.2.

I have downgraded the SDK in the app to 1.0.24 which has resolved this problem for now.

**Comment by turbomerl** [comment]
Hi Jake

Many thanks for that and thanks for the update.
We will get a fix out for this as soon as possible and let you know.
Apologies for the inconvenience

All the best

Isambard

**Comment by turbomerl** [comment]
Hi Jake

I have fixed that crash and pushed up a new version of the SDK.

We have altered the way that the libraries are named. Now SourceKit supports use of the IDFA and a new version, SourceKitLight runs without it.

Therefore if you simply update your version to SourceKit 1.1.3, everything should be fine.

Once again, apologies for the crashes that you were seeing. Please don’t hesitate to get in touch if you ever have any issues.

All the best

Isambard
